### ISSUE TITLE
Merge with other gi-stub package

### ISSUE THREAD

**Issue by lovetox** [pygobject/pygobject-stubs#10]
Hi,

we developed our own gi-stub package here https://dev.gajim.org/gajim/gi-stubs

Because we want to offer it to everybody, and hope people contribute to it, we would like to ask if there is interest to merge it into this official project.

Main benefits are:

- All functions available
- Classes have all the methods
- Some methods are already typed though only the most common
- All the contstants and GEnums / GFlags are completely typed
- More gi libs (Soup, Gst, GSound, ... )

Whats missing:

- Base classes need to be added to the classes
- method args are not typed
- Think about using more elaborate concepts like Generic Types etc

**Comment by MrinmoyHaloi** [comment]
Looks great. I wonder why pygobject devlopers haven't merged it yet. Atleast make the current stubs better

**Comment by lazka** [comment]
@lovetox I gave you maintainer rights here.

**Comment by lazka** [comment]
One thing I never found a good answer for was what to do with Gtk3 vs Gtk4 for example. Except adjust pygobject to allow versioned imports like `from gi.repository import Gtk_3_0 as Gtk` or something.

**Comment by lovetox** [comment]
Thanks @lazka i merged it.

for the Gtk3 / 4 discussion i would open a new issue as it would be offtopic here, maybe other people have also ideas

**Comment by lazka** [comment]
ok, let me know when I should push to pypi, or if you want to be added there as well.

**Comment by lovetox** [comment]
I am not very experienced with pypi so would be great if you could keep doing that.
i think it makes sense to just push a new version as soon as possible.

is there a preferred way how to reach you? mail? gitter?

if you push a new version, i noticed that your mail address in setup.py has a typo

**Comment by lazka** [comment]
> I am not very experienced with pypi so would be great if you could keep doing that. i think it makes sense to just push a new version as soon as possible.

OK

> is there a preferred way how to reach you? mail? gitter?

Whatever you prefer. github is fine too.

> if you push a new version, i noticed that your mail address in setup.py has a typo

thanks, fixed
