### ISSUE TITLE
Is --no-cache-dir required in order to update from Gtk4 to Gtk3 or vice versa

### ISSUE THREAD

**Issue by slabko** [pygobject/pygobject-stubs#113]
If I accidentally install the package without any `--config-settings` then I get stubs for the the latest Gtk4 version. If I wanna fix my mistake and install stubs for Gtk3 just using 
```pip install --force-reinstall --config-settings=config=Gtk3,Gdk3,Soup2 pygobject-stubs```
gives the same Gtk4 stubs.

The only way to fix that for me was using `--no-cache-dir`:
```pip install --force-reinstall --config-settings=config=Gtk3,Gdk3,Soup2 pygobject-stubs```

I was wondering if I missed anything here, or it is required to switch the version of stubs.

**Comment by lovetox** [comment]
yes seems --no-cache-dir is necessary. I will amend the README.

I consider this a bit of a pip bug though. I will open a issue with them also.
