### ISSUE TITLE
Support for Rsvg ?

### ISSUE THREAD

**Issue by ydirson** [pygobject/pygobject-stubs#116]
It would be great to gain a stub for Rsvg

**Comment by lovetox** [comment]
Seems you know how to make a pull request, its just a matter of running the generator and commiting the result.

See https://github.com/pygobject/pygobject-stubs/blob/master/CONTRIBUTING.md

**Comment by ydirson** [comment]
Started to go that way already, slowed down by the fact the script uses too recent constructs for 3.9, but yeah I'll manage ;)
