### ISSUE TITLE
Automated publish to pypi via Actions

### ISSUE THREAD

**Issue by lovetox** [pygobject/pygobject-stubs#13]
We could add a Github action to publish automatically on release

there is a public Action for that available, all you need to add is a secret API token from pipy

@lazka i can setup the action but it seems i dont have access to the token settings, could you look into it if you have time?

**Comment by lazka** [comment]
let me check

**Comment by lazka** [comment]
ok, pypi allows creating project specific tokens, so this is at least possible.

**Comment by lazka** [comment]
I've pushed the current state as a new release for starters

**Comment by lazka** [comment]
As I said before, I can also add you as a co-maintainer on pypi (as long as you use 2FA) then you could create your own tokens.

**Comment by lovetox** [comment]
Ok i setup an account, you can find me under my username or email

**Comment by lovetox** [comment]
So i have now created the secret on pipy but i dont have enough permission to set it on this repository

**Comment by lazka** [comment]
try again now

**Comment by lovetox** [comment]
Thanks works now

**Comment by lazka** [comment]
nice :)

**Comment by lovetox** [comment]
just if you don’t know, its now setup so you just have to add a tag/release in the github UI and afterwards the action automatically publishes the release
