### ISSUE TITLE
GObject.GError is an alias of GLib.Error but for some reasons has distinct typehints

### ISSUE THREAD

**Issue by theCapypara** [pygobject/pygobject-stubs#156]
At runtime `GObject.GError` is just an alias for `GLib.Error`. But for some reasons the typestubs treat them as different types, with the `GError` stubs being very incomplete.

**Comment by lovetox** [comment]
Ok, so could you not simply use GLib.Error?

The docs say

> GObject.GError is deprecated; use GLib.GError instead

just wonder if its worth it to actually do here something, if you could simply replace GError in your codebase

**Comment by lovetox** [comment]
I checked this again GObject.GError is deprecated, i see no alias for it

GLib.Error is an alias of GLib.GError

All stubs are incomplete, i will try to add hints for them
