### ISSUE TITLE
Gst: Event.new_buffer_size has syntactically invalid argument name

### ISSUE THREAD

**Issue by jtojnar** [pygobject/pygobject-stubs#172]
`async` is not allowed as argument name here:

https://github.com/pygobject/pygobject-stubs/blob/53418d5e5f705645d2122022e129365d6f35bef5/src/gi-stubs/repository/Gst.pyi#L2037

so black will complain:

```
error: cannot format /home/jtojnar/Projects/pygobject-stubs/src/gi-stubs/repository/Gst.pyi: Cannot parse: 2037:73:     def new_buffer_size(cls, format: Format, minsize: int, maxsize: int, async: bool) -> Event: ...
```

**Comment by lovetox** [comment]
this is because you dont use the `-o` argument when running the generator. This method has been typed manually to account for this.
