### ISSUE TITLE
Add a license for the project

### ISSUE THREAD

**Issue by MrinmoyHaloi** [pygobject/pygobject-stubs#18]
There should be a license for the project. Most of the open source projects have them. The PyGobject project uses LGPL v2.1. And two other projects in the pygobject organization uses it. So I guess this repository should also use that.

**Comment by lovetox** [comment]
@lazka ok for you?

**Comment by MrinmoyHaloi** [comment]
We need to get permission from all of the contributors of the repository in order to change the license. @lovetox, @lazka, @wurstsalat3000 and me(I have already approved)

**Comment by lazka** [comment]
https://spdx.org/licenses/LGPL-2.1-or-later.html sounds good/practical to me

**Comment by wurstsalat3000** [comment]
Ok by me!

**Comment by lovetox** [comment]
also ok for me, @MrinmoyHaloi would be great if you could provide the MR. thanks

**Comment by MrinmoyHaloi** [comment]
ok making it

**Comment by MrinmoyHaloi** [comment]
Its called PR, pull request
