### ISSUE TITLE
Please add this to pygobject's document

### ISSUE THREAD

**Issue by laoshaw** [pygobject/pygobject-stubs#36]
This is the key piece missing from PyGObject, in that it lacks typeshed or its own pyi stub. It took me days to find this project. Thanks. Please add this project to all PyGObject documentations. https://github.com/pygobject/pgi-docgen/pull/176 is still a WIP.

**Comment by MrinmoyHaloi** [comment]
@lovetox any idea why this project isn't added in the documentation ?

**Comment by lovetox** [comment]
the linked project is a API documentation. I dont think it fits there. What this PR tried to do was to generate stubs automatically the same way the API docs are generated.

**Comment by MrinmoyHaloi** [comment]
it would make sense here https://pygobject.readthedocs.io/en/latest/devguide/dev_environ.html @lovetox

**Comment by lovetox** [comment]
MR created https://gitlab.gnome.org/GNOME/pygobject/-/merge_requests/225

you can follow this issue there
