### ISSUE TITLE
how do you install it?

### ISSUE THREAD

**Issue by Pshemas** [pygobject/pygobject-stubs#37]
Do I have to do anything apart from :
```pip install PyGObject-stubs```

I wonder, as I'm trying to use it to get rid of pyright error reports. Pip install fixes complaining about Gtk symbol, but now I get:
```No named parameter:title```
on this line:
```window = Gtk.Window(title="hello world!")```

**Comment by lovetox** [comment]
I added all possible parameters for the Window class.

Dont expect these type stubs to be complete for every class Gtk has. Currently only the most used things are typed.

Also you often have a better chance with the methods instead of kwargs.

So window.set_title()
