### ISSUE TITLE
Gtk 4 and libadwaita support

### ISSUE THREAD

**Issue by MrinmoyHaloi** [pygobject/pygobject-stubs#44]
Its been a long time since gtk4 released. December 16, 2020. almost 3 months. And also libadwaita is stable now. Shouldn't there be stubs for both of these now ?

**Comment by MrinmoyHaloi** [comment]
@lovetox what do you think

**Comment by lovetox** [comment]
This project is not fixed on any particular Gtk version.

A solution for https://github.com/pygobject/pygobject-stubs/issues/3 needs to be proposed and afterwards people can contribute Gtk4 stubs.
