### ISSUE TITLE
GObject.Object __init__ should accepts kwargs as arguments, and so should all its descendants

### ISSUE THREAD

**Issue by bicobus** [pygobject/pygobject-stubs#72]
Using these stubs, the following code would throw *Unexpected argument* warnings:

```python
Gtk.Label(
    "{}".format(text),
    halign=Gtk.Align.END,
    margin_right=5,
    margin_top=0,
    margin_bottom=10,
)
```

However, nearly all objects (if not all, didn't check) allows for passing properties as argument. As shown in the [documentation](https://lazka.github.io/pgi-docs/GObject-2.0/classes/Object.html#GObject.Object) and [sources](https://gitlab.gnome.org/GNOME/pygobject/-/blob/master/gi/pygobject-object.c#L2494-2526).

Could that behavior be reflected by the stubs?

Thanks

**Comment by lovetox** [comment]
Yeah, its a lot of work to find all arguments that can be passed from all decendents

Contributions welcome

**Comment by bicobus** [comment]
What I understand from the pygobject project, any "property" is acceptable as an argument.  You could probably look at the MRO to figure out a crude list of hidden properties. That being said, pygobject isn't even sanitizing input, as if anything is permitted. Maybe that happens later though.

**Comment by lovetox** [comment]
Did you want this for Gtk4? This should now work

**Comment by bicobus** [comment]
I'm personally still using Gtk+3, 'cause that's what is shipped with debian stable. Gtk4 will only appear in next stable, and I don't know which software will actually make use of it.

Does the stubs no longer support Gtk3?

**Comment by lovetox** [comment]
We support both, but Gtk3 has not yet been improved in this regard, so i will let this open.

**Comment by shibotto** [comment]
Out of curiosity, are you already working on this for Gtk3 or are you waiting for users contribution? I'm not exactly volunteering for now, as after generating the stubs it seems to me that there is still a lot of things I'm not sure I fully understand that need to be manually tuned.

**Comment by lovetox** [comment]
I added all kwargs to the Gtk3 module, please check if this works for you now

**Comment by bicobus** [comment]
I have a hard time installing the Gtk3 version of this package through poetry. So I can't give you a proper answer at the current time. Poetry doesn't have support for the `--config-settings` argument and for some reason I can't have poetry read my environment variable.

Beside, I'm also confused in how I get this installed properly through the various EDI available around.

**Comment by lovetox** [comment]
why are you trying to install with poetry? This is not a poetry project.

I dont see any documentation that poetry is equivalent to pip.

Whats a EDI?

**Comment by bicobus** [comment]
My project's environment is handled by poetry. I install package through poetry and keep them up to date with poetry. The whole virtual environment is dealt with poetry.

EDI → IDE. Forgive my french. Stubs are useful when using those integrated tools, notably pyCharm. I don't know how to tell pyCharm the specific way to install this package.

**Comment by bicobus** [comment]
Alright, I got my hands out of my back end and forcefully installed the stubs in the env through pip+git. Sorry for the tardiness. It works mostly. There are some weirdness though.

```py
    return Gtk.Label(
        "{}".format(text),
        halign=Gtk.Align.END,
        margin_right=5,
        margin_top=0,
        margin_bottom=10,
    )
```

Complains that the first argument isn't a float. Expects `angle`, but the documentation imply the first argument to be `label`. This might be an issue for every widget having a label, like `Gtk.Button`.

```py
Gtk.Box(Gtk.Orientation.HORIZONTAL)
```

Another order issue. Stubs expects `BaselinePosition` as first argument.

```py
    textview = Gtk.TextView(...)
    tb = textview.get_buffer()
    tb.insert(txt)  # <-
```

Complains that parameter `text` is unfulfilled. First argument from the stubs is a `TextIter`, which is news to me.

- - -

There might be more, but nothing that I can see right away.

**Comment by mat-xc** [comment]
```
>>> import gi
>>> gi.require_version("Gtk", "3.0")
>>> from gi.repository import Gtk
>>> Gtk.Label(1)
<stdin>:1: PyGTKDeprecationWarning: Using positional arguments with the GObject constructor has been deprecated. Please specify keyword(s) for "label" or use a class specific constructor. See: https://wiki.gnome.org/PyGObject/InitializerDeprecations
<Gtk.Label object at 0x7f26fd665400 (GtkLabel at 0x55f2c072e5d0)>
>>> 
```
Positional arguments are deprecated, @lovetox should we support them? Gtk4 give an error.

> Complains that parameter text is unfulfilled. First argument from the stubs is a TextIter, which is news to me.

It seems an error in the override.

**Comment by bicobus** [comment]
> Edit: The override seems good

Most likely an error on my end then. Sorry about that.

Stubs works fine then. Huzza!

**Comment by lovetox** [comment]
Yes pygobject allows it to pass some params as positional.
There is no good reason to do it though.

So i would say lets not support it for now, if more people insist on it we can come back and reevaluate.

So i close this for now
