### ISSUE TITLE
Doesn't seem to work with Gtk4

### ISSUE THREAD

**Issue by giannitedesco** [pygobject/pygobject-stubs#80]
Looks like the stubs are for Gtk3 and no way to detect the version imported via pygobject? I guess this is a fundamental limitation of the apparoach?

**Comment by lovetox** [comment]
This would be possible if this MR would get traction https://gitlab.gnome.org/GNOME/pygobject/-/merge_requests/212

**Comment by lovetox** [comment]
Gtk4 stubs are now the default and should work, currently no method is really typed, contributions welcome.
