### ISSUE TITLE
PyCharm IDE: Stubs for binary module (GTK) won't generate from remote interpreter

### ISSUE THREAD

**Issue by acirulis** [pygobject/pygobject-stubs#9]
What steps will reproduce the problem?

Have remote Debian based machine with active display (tested on https://coral.ai/products/dev-board/)
Set up remote interpreter via SSH in PyCharm (2021.1) / Windows 10 to that machine
On remote machine install PyGObject (as described here https://pygobject.readthedocs.io/en/latest/getting_started.html#ubuntu-getting-started)
In PyCharm create & run basic application:
```
import gi
gi.require_version("Gtk", "3.0")
from gi.repository import Gtk

window = Gtk.Window(title="Hello World")
window.show()
window.connect("destroy", Gtk.main_quit)
Gtk.main()
```
What is the expected result?

Application will run successfully
Stubs will be created an autocomplete will be available in PyCharm
What happens instead?

Application runs successfully
Stubs are not created with error:
`Cannot find reference `Gtk` in '__init__.py'`

Please provide any additional information below.
Attach a code sample as text, a screenshot or screencast if possible

I am setting up environment for developing on Coral DevBoard (and using TPU subprocessor) and need to use Gtk, GStreamer libraries with GTK3.
Unfortunately, stubs are not generated which makes it so much harder to use these libraries. I have tried all solutions mentioned in the existing issues but they mostly focus on local development, not remote interpreter.

Installed packages:
Package             Version
------------------- -------------
certifi             2020.12.5
chardet             4.0.0
cloudpickle         1.6.0
cycler              0.10.0
decorator           4.4.2
distro-info         0.21
edgetpuvision       7.0
filterpy            1.1.0
gobject             0.1.0
httplib2            0.19.0
idna                2.10
imageio             2.9.0
kiwisolver          1.3.1
lap                 0.4.0
Mako                1.0.7
Markdown            3.0.1
MarkupSafe          1.1.0
matplotlib          3.3.4
netifaces           0.10.9
networkx            2.5
numpy               1.20.1
Pillow              8.1.2
pip                 21.0.1
protobuf            3.15.6
pycairo             1.16.2
pycoral             1.0.1
pycurl              7.43.0.2
PyGObject           3.40.1
PyGObject-stubs     0.0.2
PyJWT               2.0.1
PyOpenGL            3.1.5
pyparsing           2.4.7
pyserial            3.5
PySimpleSOAP        1.16.2
python-apt          1.8.4.3
python-dateutil     2.8.1
python-debian       0.1.39
python-debianbts    3.1.0
python-periphery    2.3.0
PyWavelets          1.1.1
reportbug           7.5.3-deb10u1
requests            2.25.1
scikit-image        0.18.1
scipy               1.1.0
setuptools          40.8.0
six                 1.12.0
svgwrite            1.4.1
tflite-runtime      2.5.0
tifffile            2021.3.17
unattended-upgrades 0.1
urllib3             1.24.1
vitalsd             1.0
wheel               0.32.3

Please see also https://youtrack.jetbrains.com/issue/PY-48160 and https://youtrack.jetbrains.com/issue/PY-39158

**Comment by lovetox** [comment]
Hi, please try with the current version again. We tested these stubs with VSCode and Sublime, they work as expected, so this may be a issue with PyCharm
