### ISSUE TITLE
GLib.timeout_add_seconds has different arguments than stub.

### ISSUE THREAD

**Issue by meunomemauricio** [pygobject/pygobject-stubs#95]
My code uses `GLib.timeout_add_seconds` with `interval` and `function` as the arguments, but MyPy is complaining:

```
error: Unexpected keyword argument "interval" for "timeout_add_seconds"  [call-arg]
error: Unexpected keyword argument "function" for "timeout_add_seconds"  [call-arg]
```

The stubs indicate that the arguments should be `seconds` and `func`:

https://github.com/pygobject/pygobject-stubs/blob/94874270c23c8291a0f4196f986c1a96316e1f28/src/gi-stubs/repository/GLib.pyi#L629

But when I use those arguments, I get:

```
TypeError: timeout_add_seconds() missing 2 required positional arguments: 'interval' and 'function'
```

I'm using `require_version` for Gtk 3 and AppIndicator.

```python
import gi

gi.require_version("Gtk", "3.0")
gi.require_version("AppIndicator3", "0.1")
```

Should I be specifying a `GLib` version too?

For now, I'll just pass values as positional arguments, but I would much rather use kwargs.

**Comment by lovetox** [comment]
No this has no effect on type checking.

It seems mypy does not use the installed stubs. Our stubs dont have the words `interval` and `function`

**Comment by meunomemauricio** [comment]
@lovetox I'm not sure I understand.

Yes, the stubs don't have the words `interval`/`function`, but I believe that to be the problem. My code works just fine with those arguments, but MyPy still complains that they're unexpected.

When I try to use `seconds`/`func`, like the stubs, MyPy stops complaining, but my code doesn't work anymore. 

I'm not sure how official/trustworthy this reference is, but it shows the arguments to be `interval`/`function`: https://lazka.github.io/pgi-docs/GLib-2.0/functions.html#GLib.timeout_add_seconds

**Comment by wurstsalat3000** [comment]
Please post an example of how you are using `timeout_add_seconds`.

For python, there is an override present, which can be seen here: https://gitlab.gnome.org/GNOME/pygobject/-/blob/master/gi/overrides/GLib.py#L618

Usage can be as simple as:

```python
GLib.timeout_add_seconds(10, function, args)
```

No need to use named args.

**Comment by lovetox** [comment]
He uses the method with keyword arguments

`GLib.timeout_add_seconds(interval=10, function=function, args)`

this fails because we dont use interval and function as argument names.

Short answer we should change this, to the arg names the docs use.

**Comment by meunomemauricio** [comment]
Excellent. Thanks for the quick response!
